spring.application.name=WeatherApp

spring.profiles.active=dev

visualcrossing.api.key=${WEATHER_API_KEY}
visualcrossing.api.base-url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline